### PR TITLE
fixed responsiveness in header on the countries page

### LINKED ISSUE #446: Header on the countries page is not reponsive in mobile-view
## Expected Behavior
In desktop view the Countries-header is responsive ie- It displays the continents and search .

Screenshot from 2020-03-28 01-30-16

## Actual Behavior
In mobile-view it is not the same. All continent names are not visible and so is the search

Screenshot_20200325-004523

## Steps to Reproduce the Problem

  1. Click on `Countries`
 
## Specifications

  - Platform: mobile

### PR DESCRIPTION
**Pull request by NidhiKJha**
Fixes #446 

This pull request adds the responsiveness in mobile -view

1. Desktop-view
Screenshot from 2020-04-27 00-56-54

2. Mobile-view
Screenshot from 2020-04-27 00-56-35

### CODE REVIEW

**Comment by NidhiKJha** [comment]
@sarathms @hellais please review my pull request. My implementation differs a bit from the mockup you provided. Please let me know if you want me to change it. Thank you :)

File: pages/countries.js [hunk 1]
```diff
@@ -118,9 +118,9 @@ const StyledRegionLink = styled.a`
 `
 
 const RegionLink = ({ href, label }) => (
-  <Box px={3} py={4}>
+  <Box px={[1,3]} py={[2,4]}>
```
Comment (sarathms) [inline pages/countries.js:121]: Vertical spacing `py` can go one step higher here.

Comment (NidhiKJha) [reply pages/countries.js:121]: I tried increasing the `py` but it was not going perfectly with the UI so I didn't change it.

**Comment by NidhiKJha** [comment]
Hi @sarathms ! I have made changes in the positioning of the search but without using order.(But thanks for mentioning the use of order I learnt it :p) Please let me know if I have missed something. Thank You :)

**Comment by NidhiKJha** [comment]
In the mockups, there is a underlining in the Africa. I tried to add it. But I couldn't. This was my approach. Please let me know how should I approach :)


```const Underline = styled.span
  display: block;
  height: 2px;
  background: ${props => props.theme.colors.blue5};
  width: ${props => props.active ? '100%' : '0px'};
`

const _RegionLink = ({ router, href, label }) => {
  const checkActive = href === router.asPath.replace('/countries', '')
  const [active, setActive] = React.useState(checkActive)
  console.log("test", href, active)

  return (
    <Box px={[1,3]} py={[2,4]}>
      <StyledRegionLink onClick={() => setActive(checkActive)} href={href}>
        <Text fontSize={[14, 20]}>{label}</Text>
        <Underline active={active}/>
      </StyledRegionLink>
    </Box>
  )
}

const RegionLink =  withRouter(_RegionLink)

**Comment by sarathms** [comment]
> In the mockups, there is a underlining in the Africa

The approach you mentioned above is also good and that's how the NavBar links are styled. Alternatively, you can try hover styling with `border-bottom` inside `StyledRegionLink` but applied to its child `Text`
Something like this:
```javascript
const StyledRegionLink = styled.a`
  ...
  & > ${Text}:hover {
     display: inline;
     border-bottom: 2px solid ${blue5 color from theme};
  }
`
```
The `display: inline` is crucial.

File: components/NavBar.js [hunk 2]
```diff
@@ -18,7 +18,7 @@ const StyledNavItem = styled.a`
   text-decoration: none;
   position: relative;
   display: inline;
-  margin-left: 16px;
+  margin-left: 23px;
```
Comment (sarathms) [inline components/NavBar.js:21]: It looks better to use something in the scale `2, 4, 8, 16, 32` for spacing values wherever possible. In this case, `32px`

File: components/NavBar.js [hunk 3]
```diff
@@ -73,7 +73,7 @@ export const NavBar = ({color}) => (
         flexDirection={['column', 'row']} 
         justifyContent={['flex-start', 'space-around']} 
         alignItems={['flex-start', 'center']} >
-        <Box style={{zIndex: 1}}>
+        <Box ml={23} style={{zIndex: 1}}>
```
Comment (sarathms) [inline components/NavBar.js:76]: Lets revert this and leave the logo aligned to the left edge of that `Flex`. The `Container` already takes care of those margins.

File: pages/countries.js [hunk 4]
```diff
@@ -201,24 +201,23 @@ class Countries extends React.Component {
                 <NavBar />
                 <RegionMenu>
                   <Container>
-                    <Box width={[1, 'unset']}>
+                    <Box ml={23} width={1}>
```
Comment (sarathms) [inline pages/countries.js:204]: It seems this `Box` doesn't have a purpose anymore. If removing it doesn't change anything, please remove it.

File: components/NavBar.js (hunk 2 above)
Comment (sarathms) [reply components/NavBar.js:21]: On second thought, instead of this `margin-left` maybe the `StyledNavItem`s should be enclosed in `Box`es and use `ml=[0, 4]` to make them responsive.

Comment (NidhiKJha) [reply components/NavBar.js]: I have added the `Box` here

File: pages/countries.js (hunk 4 above)
Comment (NidhiKJha) [reply pages/countries.js]: Removed it

**Comment by NidhiKJha** [comment]
Hi @sarathms I have made all the changes suggested by you. Please review the pull request. Thanks :)
