### PR TITLE
Handle missing test keys

### LINKED ISSUE #416: Ensure pages render minimal content when `test_keys` are missing
Currently pages crash when `test_keys` dictionary doesn't contain keys being used to render the page. One such bug in Web Connectivity measurement page was reported #414 and fixed recently.

A `try...catch` based approach to this problem is generally handled in React by using the [Error Boundaries](https://reactjs.org/docs/error-boundaries.html). But this doesn't work well in SSR environments like Next.js.

### PR DESCRIPTION
**Pull request by sarathms**
Fixes #416 

Makes sure all measurement pages render without crashing when any of the keys  in `test_keys`are not found in the measurement.

Also includes a development toolbar (not added to any pages) that allows us to control the values inside different `test_keys`
image

### CODE REVIEW

File: components/measurement/nettests/HTTPHeaderFieldManipulation.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ export const HttpHeaderFieldManipulationDetails = ({ measurement, render }) => {
       isFailed = false
     }
   })
-  const headerDiff = testKeys.tampering.header_name_diff
+  // const headerDiff = testKeys.tampering.header_name_diff
```
Comment (bassosimone) [inline components/measurement/nettests/HTTPHeaderFieldManipulation.js:21]: I suggest to remove code we don't need rather than commenting it out. We have git history and we are doing a great job w/ commits, so it shan't be a problem in the future to go back and ask our past self a hand.

File: components/measurement/nettests/HTTPHeaderFieldManipulation.js [hunk 2]
```diff
@@ -32,7 +32,7 @@ export const HttpHeaderFieldManipulationDetails = ({ measurement, render }) => {
       details: (
         <div>
           {/*<Text>isAnomaly: {isAnomaly.toString()}</Text>
-          <Text>isFailed: {isFailed.toString()}</Text>
+            <Text>isFailed: {isFailed.toString()}</Text>
```
Comment (bassosimone) [inline components/measurement/nettests/HTTPHeaderFieldManipulation.js:35]: Same as above. I'd like to encourage you to not keep commented out code. Commented out code rots twice as fast as comments describing implementations, so I'd be mostly pleased if we can avoid it.

File: components/measurement/nettests/Ndt.js [hunk 3]
```diff
@@ -55,27 +56,44 @@ const NdtDetails = ({ measurement, render }) => {
...
+        mss={mss}
+        packetLoss={packetLoss}
+        outOfOrder={outOfOrder}
+        timeouts={timeouts}
+      />
+    )
+  } catch (e) {
+    console.error(`Error in parsing test_keys for ${measurement.test_name}`)
+    console.error(e)
+    // Leaves performanceDetails `null` and thus isn't rendered
```
Comment (bassosimone) [inline components/measurement/nettests/Ndt.js:96]: Thanks for this comment!

File: components/measurement/useTestKeyController.js [hunk 4]
```diff
@@ -0,0 +1,71 @@
+import React, { useState, useCallback } from 'react'
+import { Flex } from 'ooni-components'
+
+// Custom hook to render a toolbar to enable/disable parts of `testKeys`
+// Usage: Add this to the MeasurementContainer
```
Comment (bassosimone) [inline components/measurement/useTestKeyController.js:5]: Again, I'd like to praise this correct usage of comments to explain the purpose of commented out code

File: components/measurement/useTestKeyController.js [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+
+  const TestKeyController = () => {
+    const onChange = useCallback((event) => {
+      const {name, checked} = event.target
+
+      if (name === 'all') {
+        setTestKeys(checked ? testKeysInitial : {})
+        setKeysMap(setValues(testKeysInitial, checked))
+        return
+      } else {
```
Comment (bassosimone) [inline components/measurement/useTestKeyController.js:40]: I'd like to encourage you to avoid `if () { ... return } else { ... }`. Why don't we follow instead the Okkam razor's principle where we don't include an else branch when we don't need it?

File: components/measurement/useTestKeyController.js (hunk 4 above)
Comment (bassosimone) [reply components/measurement/useTestKeyController.js:5]: I'd perhaps just rephrase the comment to say "This file ..." such that it's clear what is the purpose of this very useful piece of code, which otherwise may not be fully obvious at a first glance.

**Review by bassosimone — APPROVED** [review]
Thank you, I really like what I see. Please, consider applying the recommended changes, which mainly amount to tiny changes to slightly improve reliability. 🐳

File: components/measurement/useTestKeyController.js (hunk 4 above)
Comment (sarathms) [reply components/measurement/useTestKeyController.js:5]: Done. Another way to do this would be to use the `NODE_ENV === 'development'` flag to make it available in dev mode. But this isn't that frequently used either.

File: components/measurement/useTestKeyController.js (hunk 5 above)
Comment (sarathms) [reply components/measurement/useTestKeyController.js:40]: Thanks. You are right. I have now changed it to a simple exclusive `if ... then` structure. Earlier I wrote some common steps at the end, which eventually changed.

**Comment by sarathms** [comment]
I have addressed the comments. I made a [small change](https://github.com/ooni/explorer/pull/491/commits/7bfb746e4c6fdb9fe44cf096ced107a7f3ab9795#diff-7cde3a620c68a1903572470a0c0c8525) that makes it easy to follow the [usage described here](https://github.com/ooni/explorer/pull/491/commits/55b6a8efc35f3ebaf2dd22fc59b0a9b4b1985a13#diff-97b0c9b852cc7bf9fc615ad99c41e79e). Since it is a trivial one, I am going ahead and merging this.
