### PR TITLE
Handle AAAA answers in DNS queries

### LINKED ISSUE #500: DNS queries with AAAA answers causes web_connectivity measurement pages to crash
[example measurement](https://explorer.ooni.org/measurement/20201002T173034Z_AS0_X5fQaoPjGfg73APaJSMCGjAd5gSWSG07SHEZtXHnDb4yvpvU1u?input=http%3A%2F%2Fwww.iea.org%2F)

Problem: We only look for DNS response types `A` and `CNAME`, for rest of the types, we pass in an object to a component (`DnsAnswerCell`) that can only render strings, components or elements.

Possible solutions:
1) Make `DnsAnswerCell` handle an object in its `props.children` to render
2) Have logic to handle all possible `answer_type` values. Refer https://github.com/ooni/spec to know what to expect
3) Fallback values to use when the `answer` is corrupt

### PR DESCRIPTION
**Pull request by sarathms**
Fixes #500 

Now we show ipv4 for `A` type, `ipv6` for `AAAA` and `hostname` for `CNAME` and ignore everything else.

### CODE REVIEW

File: components/measurement/nettests/WebConnectivity.js [hunk 1]
```diff
@@ -287,12 +304,6 @@ const WebConnectivityDetails = ({
     timeZone: 'UTC',
     timeZoneName: 'short'
   })
-  const reasons = {
-    'http-diff': 'HTTP-diff',
-    'http-failure': 'HTTP-failure',
-    'dns': 'DNS',
-    'tcp_ip': 'TCP'
-  }
```
Comment (bassosimone) [inline components/measurement/nettests/WebConnectivity.js:295]: I assume this was unused correct?

**Review by bassosimone — APPROVED** [review]
🐳 

asked a question just to be sure I understand

File: components/measurement/nettests/WebConnectivity.js (hunk 1 above)
Comment (sarathms) [reply components/measurement/nettests/WebConnectivity.js:295]: Yes
