### PR TITLE
Fix measurement pages copy

### LINKED ISSUE #95: Force word-wrap on measurement id in measurment pages
Since it is a long string, it overflows even in full width layouts. Use `word-wrap: break-word;` to forcefully break the text to the next line.

### LINKED ISSUE #115: Display the blocking reason/technique in measurement pages
In anomalous & confirmed blocked measurement pages, the summary paragraph includes the "Blocking Reason" key (e.g. Measurement.SummaryText.Websites.Anomaly.BlockingReason.HTTP), but not the actual copy. For example: http://explorer-beta.ooni.io/measurement/20190501T153831Z_AS37424_BOSFQB55tqBEEQQ7I6fYukt05dP0T6JhEdfwHxCJQj3Msz1EaA?input=http://www.pandora.com/ & http://explorer-beta.ooni.io/measurement/20190501T085412Z_AS42668_zDAYOOjqswLhfCTZE12M8TYKXDY0BgP8RWTi10wY6R6OXwC9To?input=http://kinokubik.org/

blocking reason

### LINKED ISSUE #118: Display Summary Text on measurement pages of IM & middlebox tests
The summary text (i.e. the copy for the key "Measurement.Details.SummaryTextTemplate") is missing in the measurement pages of the following tests:

* WhatsApp: http://explorer-beta.ooni.io/measurement/20190501T155307Z_AS12389_by8uA53xrB272KYRlV2PWU3hDH1G53V3cXioDX0kqWvZr5knuw

* Facebook Messenger: http://explorer-beta.ooni.io/measurement/20190501T233832Z_AS37424_Kxlw23qwyVTx5rjMSZUhpaSMXHVFnADr8ifZJ97oJSM4aZaV9m

* Telegram: http://explorer-beta.ooni.io/measurement/20190502T002851Z_AS4788_R8Nkp367QGJPVEZQLKRCfEbgLsW7yu88reiBf4l8GDtr4zHKHJ

* HTTP Invalid Request Line: http://explorer-beta.ooni.io/measurement/20190502T002326Z_AS53877_0TUILJOXmiM2qvqRO0cIvwLdWx4O0NLQLgodAuZQXOUYywMAQ0

* HTTP Header Field Manipulation: http://explorer-beta.ooni.io/measurement/20190502T002949Z_AS4922_PSArZ1SI8ip1888y6AFzfWVrXRhCrjbwaxYRQOgdGNb1CoiKf8

### LINKED ISSUE #120: Display copy for Telegram endpoint label keys
The copy for the following Telegram keys (in the measurement page) is missing:

* Measurement.Details.Telegram.Endpoint.Label.Web

* Measurement.Details.Telegram.Endpoint.Label.Mobile

See:

telegram-endpoint

Taken from: http://explorer-beta.ooni.io/measurement/20190502T002851Z_AS4788_R8Nkp367QGJPVEZQLKRCfEbgLsW7yu88reiBf4l8GDtr4zHKHJ

### PR DESCRIPTION
**Pull request by sarathms**
Fixes #118
Fixes #120
Fixes #115 
Fixes #95

### CODE REVIEW

File: components/measurement/nettests/whatsapp.js [hunk 1]
```diff
@@ -35,13 +35,20 @@ const WhatsAppDetails = ({ measurement, render }) => {
...
   if (possibleCensorship || !working) {
     status = 'anomaly'
     info = <FormattedMessage id='Measurement.Status.Hint.WhatsApp.Blocked' />
-    summaryText = <FormattedMessage id='Measurement.Details.SummaryText.WhatsApp.Blocked' />
+    if (endpointsBlocked) {
+      summaryText = 'Measurement.Details.SummaryText.WhatsApp.AppFailure'
+    } else if (webBlocked) {
+      summaryText = 'Measurement.Details.SummaryText.WhatsApp.DesktopFailure'
+    } else if (endpointsBlocked && webBlocked) {
+      summaryText = 'Measurement.Details.SummaryText.WhatsApp.DesktopAndAppFailure'
```
Comment (hellais) [inline components/measurement/nettests/whatsapp.js]: I am not sure it's entirely accurate to call this still `summaryText` as it's in fact the `key` to the text.

File: components/measurement/nettests/facebook_messenger.js [hunk 2]
```diff
@@ -33,24 +34,46 @@ export const FacebookMessengerDetails = ({ measurement, render }) => {
...
+    if (tcpBlocking) {
+      summaryText += intl.formatMessage({id: 'Measurement.Details.SummaryText.FacebookMessenger.TCPFailure'})
+    } else {
+      summaryText += intl.formatMessage({id: 'Measurement.Details.SummaryText.FacebookMessenger.TCPSuccess'})
+    }
+
+    if (dnsBlocking) {
+      summaryText += intl.formatMessage({id: 'Measurement.Details.SummaryText.FacebookMessenger.DNSFailure'})
+    } else {
+      summaryText += intl.formatMessage({id: 'Measurement.Details.SummaryText.FacebookMessenger.DNSSuccess'})
```
Comment (hellais) [inline components/measurement/nettests/facebook_messenger.js]: It seems like you are mixing in here the use of the `summaryText` variable for both `FormattedMessage` `id` key values and also the actual translated string.

Does this work as expected?

**Comment by hellais** [comment]
There are now some conflicts with this PR and the other open ones :|

**Comment by sarathms** [comment]
Resolved the conflicts. I am guessing this should resolve conflicts in others as well when this lands in master.

File: components/measurement/nettests/facebook_messenger.js (hunk 2 above)
Comment (sarathms) [reply components/measurement/nettests/facebook_messenger.js]: Turns out it is a bug, yet works as expected. It was certainly not intended this way. `react-intl` fails to find the key and prints the key itself as the message.

I have [modified `SummaryText`](https://github.com/ooni/explorer/pull/146/files#diff-77ee24bf0b058edd4a84b18feaddef79) to accept either a `function`, `string`, or `any` in the `content` prop and render them accordingly. The problem with `string` type is that it cannot distinguish between the `react-intl` key and an actual string to be rendered (in this case already formatted).

One fix is sending the key as an object to the `content` prop e.g `content={{ key: 'Measurement.Test.SummaryText.Reason'}}` with additional values if needed. And handle it the way `typeof content === 'string'` is handled right now. And render strings as is.

I feel the measurement details section in general and the SummaryText component in particular have gone through many iterations and I haven't been able to apply the patterns consistently across `components/measurement/nettests/*.js` files. I wonder if I should refactor it based on what we know now about what we want.

File: components/measurement/nettests/whatsapp.js (hunk 1 above)
Comment (sarathms) [reply components/measurement/nettests/whatsapp.js]: Related to the conversation below.

File: components/measurement/nettests/facebook_messenger.js (hunk 2 above)
Comment (hellais) [reply components/measurement/nettests/facebook_messenger.js]: I understand. Maybe file an issue related to this part of refactoring so that we don't forget about it and we can proceed with merging this as is for the time being.

Comment (hellais) [reply components/measurement/nettests/facebook_messenger.js]: https://github.com/ooni/explorer/issues/156
